namespaces:
  nubbeprop: http://nubbe.db/property/
  nubbeclass: nubbe.db/class/
  nubberesource: http://nubbe.db/
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
mappings:
  nubbeprop:code
  nubbeprop:smile
  rdfs:label
  rdf:type
  rdfs:comment
  nubbeprop:molecularMass
  nubbeprop:monoisotropicMass
  nubbeprop:cLogP
  nubbeprop:tpsa
  nubbeprop:numberOfLipinskiViolations
  nubbeprop:numberOfH-bondAcceptors
  nubbeprop:numberOfH-bondDonors
  nubbeprop:numberOfRotableBonds
  nubbeprop:molecularVolume
  nubbeprop:doi
  nubbeprop:biologicalActivity
  nubbeprop:collectionSpecie
  nubbeprop:collectionSite
  nubbeprop:collectionType