mapping:
  - nubbe:code
  - nubbe:hasSMILE
  - rdfs:label
  - rdfs:Class
  - rdfs:comment
  - nubbe:hasMolecularMass
  - nubbe:hasMolecularMass
  - nubbe:hasMonoisotropicMass
  - nubbe:has-cLogP
  - nubbe:hasTPSA
  - nubbe:numberOfLipinskiViolations
  - nubbe:numberOfH-bondAcceptors
  - nubbe:numberOfH-bondDonors
  - nubbe:numberOfRotableBonds
  - nubbe:hasMolecularVolume
  - nubbe:hasCollectionSite
  - nubbe:hasBiologicalActivity
  - nubbe:hasOrigin
  - nubbe:foundInSpecie